List<Map<String, dynamic>> apiDataFoodList = [
  {
    'id': '1',
    'categoryId': '1',
    'code': 'Value1',
    'name':
        'Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1Value1',
    'price': 100000,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://classroomclipart.com/image/static7/preview2/plate-of-sushi-clip-art-59346.jpg',
    'status': 1,
  },
  {
    'id': '2',
    'categoryId': '2',
    'code': 'Value2',
    'name': 'Value2',
    'price': 1000010,
    'description': 'Value2',
    'isCombo': false,
    'imagePath':
        'https://classroomclipart.com/image/static7/preview2/plate-of-sushi-clip-art-59346.jpg',
    'status': 1,
  },
  {
    'id': '3',
    'categoryId': '1',
    'code': 'Value3',
    'name': 'Value3',
    'price': 1002000,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://classroomclipart.com/image/static7/preview2/taco-with-tomato-lettuce-meat-clip-art-59423.jpg',
    'status': 1,
  },
  {
    'id': '4',
    'categoryId': '4',
    'code': 'Value4',
    'name': 'Value4',
    'price': 1000300,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://classroomclipart.com/image/static7/preview2/taco-with-tomato-lettuce-meat-clip-art-59423.jpg',
    'status': 1,
  },
  {
    'id': '5',
    'categoryId': '5',
    'code': 'Value5',
    'name': 'Value5',
    'price': 1000040,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://classroomclipart.com/image/static7/preview2/taco-with-tomato-lettuce-meat-clip-art-59423.jpg',
    'status': 1,
  },
  {
    'id': '6',
    'categoryId': '1',
    'code': 'Value6',
    'name': 'Value6',
    'price': 1000005,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://www.freepnglogos.com/uploads/food-png/food-png-transparent-images-png-only-22.png',
    'status': 1,
  },
  {
    'id': '7',
    'categoryId': '1',
    'code': 'Value7',
    'name': 'Value7',
    'price': 100000,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://www.freepnglogos.com/uploads/food-png/food-png-transparent-images-png-only-22.png',
    'status': 1,
  },
  {
    'id': '8',
    'categoryId': '1',
    'code': 'Value8',
    'name': 'Value8',
    'price': 1000100,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://www.pngkey.com/png/full/907-9070330_food-clipart-png-healthy-foods-clipart-png.png',
    'status': 1,
  },
  {
    'id': '9',
    'categoryId': '1',
    'code': 'Value9',
    'name': 'Value9',
    'price': 100000,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://www.pngkey.com/png/full/907-9070330_food-clipart-png-healthy-foods-clipart-png.png',
    'status': 1,
  },
  {
    'id': '10',
    'categoryId': '1',
    'code': 'Value10',
    'name': 'Value10',
    'price': 1000030,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://www.pngkey.com/png/full/907-9070330_food-clipart-png-healthy-foods-clipart-png.png',
    'status': 1,
  },
  {
    'id': '11',
    'categoryId': '1',
    'code': 'Value11',
    'name': 'Value11',
    'price': 100000,
    'description': 'Value1',
    'isCombo': false,
    'imagePath':
        'https://i.pinimg.com/originals/ee/28/89/ee288996db69afeb8ec5cbf84f8c0d10.jpg',
    'status': 1,
  },
];

List<Map<String, dynamic>> apiDataSchoolList = [
  {
    'id': '1',
    'areaId': '1',
    'kitchenId': 'Value1',
    'code': 'Value1',
    'name': 'Value1',
    'address': 'Value1',
    'imagePath':
        'https://static.vecteezy.com/system/resources/previews/015/529/452/non_2x/100th-day-of-school-cartoon-colored-clipart-free-vector.jpg',
    'status': 1,
  },
  {
    'id': '2',
    'areaId': '1',
    'kitchenId': 'Value1',
    'code': 'Value2',
    'name': 'Value2',
    'address': 'Value1',
    'imagePath':
        'https://static.vecteezy.com/system/resources/previews/015/529/452/non_2x/100th-day-of-school-cartoon-colored-clipart-free-vector.jpg',
    'status': 1,
  },
  {
    'id': '3',
    'areaId': '1',
    'kitchenId': 'Value1',
    'code': 'Value1',
    'name': 'Value1',
    'address': 'Value1',
    'imagePath':
        'https://static.vecteezy.com/system/resources/previews/015/529/452/non_2x/100th-day-of-school-cartoon-colored-clipart-free-vector.jpg',
    'status': 1,
  },
  {
    'id': '4',
    'areaId': '1',
    'kitchenId': 'Value1',
    'code': 'Value4',
    'name': 'Value4',
    'address': 'Value1',
    'imagePath':
        'https://static.vecteezy.com/system/resources/previews/015/529/452/non_2x/100th-day-of-school-cartoon-colored-clipart-free-vector.jpg',
    'status': 1,
  },
  {
    'id': '5',
    'areaId': '1',
    'kitchenId': 'Value1',
    'code': 'Value5',
    'name': 'Value5',
    'address': 'Value5',
    'imagePath':
        'https://static.vecteezy.com/system/resources/previews/015/529/452/non_2x/100th-day-of-school-cartoon-colored-clipart-free-vector.jpg',
    'status': 1,
  },
];

List<Map<String, dynamic>> apiDataKitchenList = [
  {
    'id': '1',
    'areaId': '1',
    'code': 'Value1',
    'name': 'Value1',
    'address': 'Value1',
    'imagePath':
        'https://static.vecteezy.com/system/resources/thumbnails/011/743/306/small/kitchen-logo-design-illustration-vintage-menu-for-the-restaurant-vector.jpg',
    'status': 1,
  },
  {
    'id': '2',
    'areaId': '1',
    'code': 'Value2',
    'name': 'Value2',
    'address': 'Value1',
    'imagePath':
        'https://www.zarla.com/images/zarla-our-kitchen-1x1-2400x2400-20211105-h3rkb8t4qvc74kx6bjpt.png',
    'status': 1,
  },
];

List<Map<String, dynamic>> apiDataMenuList = [
  {
    'id': '1',
    'kitchenId': '1',
    'creatorId': 'Value2',
    'updaterId': 'Value1',
    'code': 'Value1',
    'createDate': '2024-01-18 16:40:00.000',
    'updateDate': '2024-01-18 16:40:00.000',
    'status': 1,
  },
  {
    'id': '2',
    'kitchenId': '1',
    'creatorId': 'Value2',
    'updaterId': 'Value1',
    'code': 'Value2',
    'createDate': '2024-01-18 16:40:00.000',
    'updateDate': '2024-01-18 16:40:00.000',
    'status': 1,
  },
];
List<Map<String, dynamic>> apiDataOrderList = [
  {
    'id': '1',
    'sessionDetailId': '1',
    'profileId': 'Value1',
    'code': 'Value1',
    'totalPrice': 30000,
    'paymentDate': '2024-01-18 16:40:00.000',
    'deliveryDate': '2024-01-18 16:40:00.000',
    'rewardPoints': 1,
    'feedback': 'feedback',
    'status': 1,
  },
  {
    'id': '2',
    'sessionDetailId': '1',
    'profileId': 'Value2',
    'code': 'Value2',
    'totalPrice': 100000,
    'paymentDate': '2024-01-18 16:40:00.000',
    'deliveryDate': '2024-01-18 16:40:00.000',
    'rewardPoints': 1,
    'feedback': 'feedback',
    'status': 1,
  },
  {
    'id': '3',
    'sessionDetailId': '1',
    'profileId': 'Value3',
    'code': 'Value3',
    'totalPrice': 300000,
    'paymentDate': '2024-01-18 16:40:00.000',
    'deliveryDate': '2024-01-18 16:40:00.000',
    'rewardPoints': 31,
    'feedback': 'feedback',
    'status': 1,
  },
  {
    'id': '4',
    'sessionDetailId': '4',
    'profileId': 'Value1',
    'code': 'Value4',
    'totalPrice': 100000,
    'paymentDate': '2024-01-18 16:40:00.000',
    'deliveryDate': '2024-01-18 16:40:00.000',
    'rewardPoints': 4,
    'feedback': 'feedback',
    'status': 1,
  },
];
